// Word database - fallback when remote dictionary is unavailable

// Adult categories (18+ version)
export type AdultCategory = 'party' | 'dirty';

// Family categories (family-friendly version)
// FREE: animals, food, movies
// Premium ($1.99): sports, travel, professions
export type FamilyCategory = 'animals' | 'food' | 'movies' | 'sports' | 'travel' | 'professions';

// All possible categories
export type Category = AdultCategory | FamilyCategory;

export type Language = 'en' | 'es' | 'ua' | 'ru';

// Default built-in dictionary (used as fallback when no internet/cache)
// Uses Partial because not all categories exist for all variants
export const DEFAULT_WORD_DATABASE: Record<Language, Partial<Record<Category, string[]>>> = {
  ru: {
    party: [
      "Похмелье", "Текила", "Шот", "Бармен", "Вышибала", "Фейсконтроль", "Танцпол", "Диджей", "Кальян", "Вейп", "Блевотина", "Вертолеты", "Сушняк", "Запой", "Вписка", "Афтерпати", "Караоке", "Бодунище", "Пивной живот", "Егермейстер", "Самбука", "Абсент", "Тост", "Чокаться", "На посошок", "Штрафная", "Ерш", "Отвертка", "Кровавая Мэри", "Лонг-Айленд", "Секс на пляже", "Голубая лагуна", "Маргарита", "Мохито", "Пина Колада", "Дайкири", "Космополитен", "Б-52", "Хиросима", "Зеленая фея",
      "Бывшая", "Бывший", "Френдзона", "Свайп", "Тиндер", "Дикпик", "Нюдсы", "Подкаты", "Пикап", "Альфач", "Стерва", "Каблук", "Оленевод", "Папик", "Содержанка", "Эскорт", "Курортный роман", "Служебный роман", "Любовный треугольник", "Измена", "Ревность", "Ссора", "Примирительный секс", "Засос", "Французский поцелуй", "Обнимашки", "Свидание", "Ужин при свечах", "Лепестки роз", "Серенада", "Кольцо", "Предложение", "Мальчишник", "Девичник", "Свадьба", "Развод", "Алименты", "Тест ДНК",
      "Бюстгальтер", "Стринги", "Чулки", "Корсет", "Лабутены", "Шпильки", "Декольте", "Мини-юбка", "Топлес", "Бикини", "Силикон", "Ботокс", "Губы уточки", "Накачанная задница", "Кубики пресса", "Бицепс", "Татуировка", "Пирсинг", "Ирокез", "Борода", "Усы", "Лысина", "Парик", "Накладные ресницы", "Маникюр", "Педикюр", "Эпиляция", "Шугаринг", "Автозагар", "Солярий",
      "Прогул", "Опоздание", "Дедлайн", "Аврал", "Премия", "Штраф", "Увольнение", "Собеседование", "Корпоратив", "Тимбилдинг", "Командировка", "Отпуск", "Больничный", "Декрет", "Ипотека", "Кредит", "Долги", "Коллекторы", "Суд", "Тюрьма", "Адвокат", "Прокурор", "Судья", "Взятка", "Откат", "Распил", "Бюрократия", "Очередь", "Пробка", "ДТП", "Страховка", "Ремонт", "Соседи", "Перфоратор", "Затопили",
      "Халява", "Шара", "Блат", "Связи", "Понты", "Хайп", "Кринж", "Рофл", "Пранк", "Челлендж", "Стрим", "Донат", "Хейтер", "Тролль", "Блогер", "Инфлюенсер", "Тиктокер", "Инстаграмщица", "Фильтр", "Фотошоп", "Селфи", "Сториз", "Рики Мартин", "Бритни Спирс", "Мадонна", "Леди Гага", "Фредди Меркьюри", "Майкл Джексон", "Элвис Пресли", "Мэрилин Монро",
      "Лимузин", "Яхта", "Джет", "Особняк", "Пентхаус", "Казино", "Рулетка", "Покер", "Блэкджек", "Ставки", "Джекпот", "Лотерея", "Фортуна", "Удача", "Фарт", "Карма", "Судьба", "Гороскоп", "Гадалка", "Экстрасенс", "Приворот", "Сглаз", "Порча", "Венец безбрачия", "Холостяк", "Старая дева", "Чайлдфри", "Яжмать", "Овуляшка", "Подгузник", "Соска", "Коляска", "Роддом", "Акушерка", "Гинеколог", "Уролог", "Проктолог", "Стоматолог", "Психолог", "Психиатр", "Дурдом", "Смирительная рубашка", "Королева", "Принц", "Принцесса", "Золушка", "Белоснежка", "Русалочка",
      "Конфета", "Шоколадка", "Мармелад", "Зефир", "Торт", "Пирожное", "Пончик", "Кекс", "Печенье", "Вафли", "Пряник", "Халва", "Мороженое", "Леденец", "Жвачка", "Сироп", "Варенье", "Джем", "Мед", "Сахар", "Пицца", "Бургер", "Шаурма", "Суши", "Роллы", "Лапша", "Паста", "Стейк", "Шашлык", "Кебаб", "Плов", "Борщ", "Оливье", "Селедка под шубой", "Холодец", "Блины", "Оладьи", "Сырники", "Пельмени", "Вареники",
      "Банан", "Клубника", "Малина", "Вишня", "Арбуз", "Дыня", "Персик", "Абрикос", "Слива", "Яблоко", "Груша", "Апельсин", "Мандарин", "Лимон", "Лайм", "Грейпфрут", "Ананас", "Киви", "Манго", "Кокос", "Огурец", "Помидор", "Морковь", "Картошка", "Лук", "Чеснок", "Перец", "Капуста", "Свекла", "Горох",
      "Кошка", "Собака", "Хомяк", "Попугай", "Рыбка", "Черепаха", "Кролик", "Крыса", "Мышь", "Змея", "Паук", "Таракан", "Комар", "Муха", "Оса", "Пчела", "Бабочка", "Муравей", "Червяк", "Лягушка", "Тигр", "Лев", "Медведь", "Волк", "Лиса", "Заяц", "Еж", "Белка", "Олень", "Лось", "Слон", "Жираф", "Бегемот", "Носорог", "Зебра", "Обезьяна", "Кенгуру", "Панда", "Коала", "Ленивец",
      "Дом", "Квартира", "Дача", "Гараж", "Сарай", "Баня", "Сауна", "Бассейн", "Забор", "Ворота", "Дверь", "Окно", "Крыша", "Стена", "Пол", "Потолок", "Люстра", "Лампа", "Розетка", "Выключатель", "Диван", "Кресло", "Стул", "Стол", "Кровать", "Шкаф", "Комод", "Тумбочка", "Полка", "Зеркало", "Ковер", "Штора", "Подушка", "Одеяло", "Матрас", "Простыня", "Наволочка", "Полотенце", "Халат", "Тапочки",
      "Машина", "Автобус", "Трамвай", "Троллейбус", "Метро", "Поезд", "Самолет", "Вертолет", "Корабль", "Лодка", "Велосипед", "Самокат", "Скейт", "Ролики", "Мотоцикл", "Мопед", "Такси", "Каршеринг", "Светофор", "Переход", "Знак", "Дорога", "Мост", "Тоннель", "Парковка", "Заправка", "Мойка", "Сервис", "Колесо", "Руль", "Тормоз", "Газ", "Сцепление", "Коробка", "Двигатель", "Фары", "Дворники", "Багажник", "Капот", "Бампер",
      "Телефон", "Планшет", "Ноутбук", "Компьютер", "Монитор", "Клавиатура", "Мышка", "Принтер", "Сканер", "Флешка", "Диск", "Наушники", "Колонка", "Микрофон", "Камера", "Зарядка", "Кабель", "Розетка", "Батарейка", "Аккумулятор", "Вайфай", "Блютуз", "Интернет", "Сайт", "Приложение", "Игра", "Чат", "Почта", "Файл", "Папка"
    ],
    dirty: [
      "Сиськи", "Жопа", "Член", "Вагина", "Клитор", "Соски", "Лобок", "Промежность", "Анус", "Яички", "Мошонка", "Головка", "Крайняя плоть", "Уздечка", "Точка G", "Простата", "Матка", "Яичники", "Трубы", "Влагалище", "Половые губы", "Лоно", "Грудь", "Бедра", "Талия", "Пупок", "Шея", "Ухо", "Язык", "Губы", "Зубы", "Слюна", "Пот", "Сперма", "Смазка", "Выделения", "Месячные", "Тампон", "Прокладка",
      "Лизать", "Сосать", "Трахать", "Дрочить", "Кончать", "Глотать", "Сплевывать", "Кусать", "Царапать", "Шлепать", "Сжимать", "Тереть", "Ласкать", "Целовать", "Раздевать", "Снимать", "Надевать", "Вставлять", "Вынимать", "Двигать", "Стол", "Стул", "Кровать", "Диван", "Кресло", "Пол", "Ковер", "Душ", "Ванна", "Раковина", "Унитаз", "Стиральная машина", "Балкон", "Окно", "Лифт", "Подъезд", "Крыша", "Подвал", "Гараж", "Машина", "Заднее сиденье", "Капот", "Багажник",
      "Презерватив", "Смазка", "Лубрикант", "Масло", "Крем", "Гель", "Свечи", "Лепестки", "Шампанское", "Клубника", "Сливки", "Шоколад", "Лед", "Наручники", "Плетка", "Кляп", "Повязка", "Маска", "Костюм", "Чулки", "Пояс", "Корсет", "Бюстье", "Пеньюар", "Халат", "Полотенце", "Простыня", "Одеяло", "Подушка",
      "Любовница", "Любовник", "Секс-партнер", "Друг с привилегиями", "Случайная связь", "Секс на одну ночь", "Девственница", "Девственник", "Опытный", "Неопытный", "Скромница", "Развратница", "Нимфоманка", "Сатир", "Жиголо", "Альфонс", "Проститутка", "Шлюха", "Блядь", "Стерва", "Сучка", "Кобель", "Бабник", "Дон Жуан", "Казанова", "Ловелас",
      "Оргазм", "Эрекция", "Импотенция", "Виагра", "Сиалис", "Возбуждение", "Страсть", "Похоть", "Желание", "Влечение", "Фантазия", "Фетиш", "Комплексы", "Запреты", "Табу", "Извращение", "Норма", "Патология", "Болезнь", "Лечение", "Терапия", "Консультация", "Совет", "Опыт", "Эксперимент", "Поза", "Камасутра", "Миссионерская", "Наездница", "Догги-стайл", "69",
      "Вибратор", "Фаллоимитатор", "Анальная пробка", "Вагинальные шарики", "Вакуумная помпа", "Электростимулятор", "Секс-кукла", "Резиновая женщина",
      "Минет", "Куннилингус", "Анилингус", "Фингеринг", "Петтинг", "Вуайеризм", "Эксгибиционизм", "Стриптиз", "Лап-дэнс", "Тверк", "Глубокая глотка", "Сквирт", "Золотой дождь", "Секс по телефону", "Вирт", "Секстинг", "Порно", "Хентай", "Эротика", "Кастинги", "Вебкам", "Онлифанс", "Порнохаб", "Браззерс", "Групповой секс", "Тройничок", "Свинг", "Обмен партнерами", "Оргия", "Гэнгбэнг",
      "Секс-шоп", "Страпон", "Бондаж", "Шибари", "Порка", "Шлепки", "Укусы", "Засосы", "Стоны", "Крики", "Вздохи", "Шепот", "Грязные словечки", "Ролевые игры", "Медсестра", "Учительница", "Горничная", "Полицейский", "Сантехник", "Доставщик пиццы", "Босс", "Секретарша", "Беременность", "Контрацепция", "Таблетки", "Спираль", "Пластырь", "Кольцо", "Прерванный акт", "Венеролог", "Молочница", "Цистит", "Простатит", "Геморрой", "Грибок", "Запах", "Вкус", "Размер", "Толщина", "Длина", "Кривизна", "Волосатость"
    ]
  },
  en: {
    party: [
      "Hangover", "Tequila", "Shot", "Bartender", "Bouncer", "Face control", "Dance floor", "DJ", "Hookah", "Vape", "Vomit", "Spins", 
      "Cotton mouth", "Binge drinking", "House party", "Afterparty", "Karaoke", "Wicked hangover", "Beer belly", "Jägermeister", "Sambuca", 
      "Absinthe", "Toast", "Clink glasses", "One for the road", "Penalty shot", "Yorsh", "Screwdriver", "Bloody Mary", "Long Island", 
      "Sex on the Beach", "Blue Lagoon", "Margarita", "Mojito", "Piña Colada", "Daiquiri", "Cosmopolitan", "B-52", "Hiroshima", "Green Fairy", 
      "Ex-girlfriend", "Ex-boyfriend", "Friend zone", "Swipe", "Tinder", "Dick pic", "Nudes", "Pick-up lines", "Pick-up", "Alpha male", "Bitch", 
      "Henpecked", "Cuckold", "Sugar daddy", "Gold digger", "Escort", "Holiday romance", "Office romance", "Love triangle", "Cheating", 
      "Jealousy", "Fight", "Make-up sex", "Hickey", "French kiss", "Cuddling", "Date", "Candlelight dinner", "Rose petals", "Serenade", "Ring", 
      "Proposal", "Bachelor party", "Bachelorette party", "Wedding", "Divorce", "Alimony", "DNA test", "Bra", "Thong", "Stockings", "Corset", 
      "Louboutins", "Stilettos", "Cleavage", "Miniskirt", "Topless", "Bikini", "Silicone", "Botox", "Duck lips", "Pumped-up butt", "Six-pack", 
      "Biceps", "Tattoo", "Piercing", "Mohawk", "Beard", "Mustache", "Bald head", "Wig", "False eyelashes", "Manicure", "Pedicure", "Waxing", 
      "Sugaring", "Self-tanner", "Tanning bed", "Skipping work", "Being late", "Deadline", "Crunch time", "Bonus", "Fine", "Getting fired", 
      "Job interview", "Office party", "Team building", "Business trip", "Vacation", "Sick leave", "Maternity leave", "Mortgage", "Loan", 
      "Debts", "Debt collectors", "Court", "Prison", "Lawyer", "Prosecutor", "Judge", "Bribe", "Kickback", "Embezzlement", "Bureaucracy", 
      "Queue", "Traffic jam", "Car crash", "Insurance", "Renovation", "Neighbors", "Jackhammer", "Flooding", "Freebie", "Freeloader", 
      "Connections", "Networking", "Showing off", "Hype", "Cringe", "ROFL", "Prank", "Challenge", "Stream", "Donation", "Hater", "Troll", 
      "Blogger", "Influencer", "TikToker", "Instagram girl", "Filter", "Photoshop", "Selfie", "Stories", "Ricky Martin", "Britney Spears", 
      "Madonna", "Lady Gaga", "Freddie Mercury", "Michael Jackson", "Elvis Presley", "Marilyn Monroe", "Limousine", "Yacht", "Private jet", 
      "Mansion", "Penthouse", "Casino", "Roulette", "Poker", "Blackjack", "Betting", "Jackpot", "Lottery", "Fortune", "Luck", "Lucky streak", 
      "Karma", "Destiny", "Horoscope", "Fortune teller", "Psychic", "Love spell", "Evil eye", "Curse", "Eternal bachelor curse", "Bachelor", 
      "Old maid", "Childfree", "Momzilla", "Baby-crazy", "Diaper", "Pacifier", "Stroller", "Maternity ward", "Midwife", "Gynecologist", 
      "Urologist", "Proctologist", "Dentist", "Psychologist", "Psychiatrist", "Madhouse", "Straitjacket", "Queen", "Prince", "Princess", 
      "Cinderella", "Snow White", "Little Mermaid", "Candy", "Chocolate bar", "Marmalade", "Marshmallow", "Cake", "Pastry", "Donut", "Cupcake", 
      "Cookie", "Waffles", "Gingerbread", "Halva", "Ice cream", "Lollipop", "Chewing gum", "Syrup", "Jam", "Jelly", "Honey", "Sugar", "Pizza", 
      "Burger", "Shawarma", "Sushi", "Rolls", "Noodles", "Pasta", "Steak", "Shashlik", "Kebab", "Pilaf", "Borscht", "Olivier salad", 
      "Herring under fur coat", "Aspic", "Pancakes", "Fritters", "Cheese pancakes", "Dumplings", "Vareniki", "Banana", "Strawberry", "Raspberry", 
      "Cherry", "Watermelon", "Melon", "Peach", "Apricot", "Plum", "Apple", "Pear", "Orange", "Tangerine", "Lemon", "Lime", "Grapefruit", 
      "Pineapple", "Kiwi", "Mango", "Coconut", "Cucumber", "Tomato", "Carrot", "Potato", "Onion", "Garlic", "Pepper", "Cabbage", "Beet", "Peas", 
      "Cat", "Dog", "Hamster", "Parrot", "Fish", "Turtle", "Rabbit", "Rat", "Mouse", "Snake", "Spider", "Cockroach", "Mosquito", "Fly", "Wasp", 
      "Bee", "Butterfly", "Ant", "Worm", "Frog", "Tiger", "Lion", "Bear", "Wolf", "Fox", "Hare", "Hedgehog", "Squirrel", "Deer", "Moose", 
      "Elephant", "Giraffe", "Hippo", "Rhino", "Zebra", "Monkey", "Kangaroo", "Panda", "Koala", "Sloth", "House", "Apartment", "Country house", 
      "Garage", "Shed", "Bathhouse", "Sauna", "Swimming pool", "Fence", "Gate", "Door", "Window", "Roof", "Wall", "Floor", "Ceiling", 
      "Chandelier", "Lamp", "Socket", "Light switch", "Sofa", "Armchair", "Chair", "Table", "Bed", "Wardrobe", "Dresser", "Nightstand", "Shelf", 
      "Mirror", "Carpet", "Curtain", "Pillow", "Blanket", "Mattress", "Bedsheet", "Pillowcase", "Towel", "Bathrobe", "Slippers", "Car", "Bus", 
      "Tram", "Trolleybus", "Subway", "Train", "Airplane", "Helicopter", "Ship", "Boat", "Bicycle", "Scooter", "Skateboard", "Roller skates", 
      "Motorcycle", "Moped", "Taxi", "Car sharing", "Traffic light", "Crosswalk", "Road sign", "Road", "Bridge", "Tunnel", "Parking lot", 
      "Gas station", "Car wash", "Auto service", "Wheel", "Steering wheel", "Brake", "Gas pedal", "Clutch", "Gearbox", "Engine", "Headlights", 
      "Wipers", "Trunk", "Hood", "Bumper", "Phone", "Tablet", "Laptop", "Computer", "Monitor", "Keyboard", "Mouse", "Printer", "Scanner", 
      "Flash drive", "Disk", "Headphones", "Speaker", "Microphone", "Camera", "Charger", "Cable", "Power outlet", "Battery", 
      "Rechargeable battery", "Wi-Fi", "Bluetooth", "Internet", "Website", "App", "Game", "Chat", "Email", "File", "Folder"
    ],
    dirty: [
      "Boobs", "Ass", "Dick", "Vagina", "Clit", "Nipples", "Pubic mound", "Perineum", "Anus", "Balls", "Scrotum", "Tip", "Foreskin", "Frenulum", 
      "G-spot", "Prostate", "Uterus", "Ovaries", "Fallopian tubes", "Pussy", "Labia", "Loins", "Breasts", "Thighs", "Waist", "Belly button", 
      "Neck", "Ear", "Tongue", "Lips", "Teeth", "Saliva", "Sweat", "Cum", "Lube", "Discharge", "Period", "Tampon", "Pad", "Lick", "Suck", "Fuck", 
      "Jerk off", "Come", "Swallow", "Spit out", "Bite", "Scratch", "Spank", "Squeeze", "Rub", "Fondle", "Kiss", "Undress", "Take off", "Put on", 
      "Insert", "Pull out", "Thrust", "Table", "Chair", "Bed", "Couch", "Armchair", "Floor", "Rug", "Shower", "Bathtub", "Sink", "Toilet", 
      "Washing machine", "Balcony", "Window", "Elevator", "Stairwell", "Rooftop", "Basement", "Garage", "Car", "Back seat", "Hood", "Trunk", 
      "Condom", "Lube", "Lubricant", "Oil", "Cream", "Gel", "Candles", "Petals", "Champagne", "Strawberries", "Whipped cream", "Chocolate", 
      "Ice", "Handcuffs", "Whip", "Ball gag", "Blindfold", "Mask", "Costume", "Stockings", "Garter belt", "Corset", "Bustier", "Negligee", 
      "Robe", "Towel", "Bedsheet", "Blanket", "Pillow", "Mistress", "Lover", "Sex partner", "Friends with benefits", "Casual hookup", 
      "One-night stand", "Virgin girl", "Virgin boy", "Experienced", "Inexperienced", "Prude", "Slut", "Nymphomaniac", "Satyr", "Gigolo", 
      "Kept man", "Prostitute", "Whore", "Skank", "Bitch", "Hussy", "Stud", "Womanizer", "Don Juan", "Casanova", "Lothario", "Orgasm", 
      "Erection", "Impotence", "Viagra", "Cialis", "Arousal", "Passion", "Lust", "Desire", "Attraction", "Fantasy", "Fetish", "Insecurities", 
      "Inhibitions", "Taboo", "Perversion", "Norm", "Pathology", "Disease", "Treatment", "Therapy", "Consultation", "Advice", "Experience", 
      "Experiment", "Position", "Kama Sutra", "Missionary", "Cowgirl", "Doggy style", "69", "Vibrator", "Dildo", "Butt plug", "Ben Wa balls", 
      "Vacuum pump", "Electrostimulator", "Sex doll", "Blow-up doll", "Blowjob", "Cunnilingus", "Rimjob", "Fingering", "Petting", "Voyeurism", 
      "Exhibitionism", "Striptease", "Lap dance", "Twerking", "Deep throat", "Squirting", "Golden shower", "Phone sex", "Cybersex", "Sexting", 
      "Porn", "Hentai", "Erotica", "Casting", "Webcam", "OnlyFans", "Pornhub", "Brazzers", "Group sex", "Threesome", "Swinging", 
      "Partner swapping", "Orgy", "Gangbang", "Sex shop", "Strap-on", "Bondage", "Shibari", "Flogging", "Slapping", "Biting", "Hickeys", 
      "Moaning", "Screaming", "Sighing", "Whispering", "Dirty talk", "Role play", "Nurse", "Teacher", "Maid", "Cop", "Plumber", 
      "Pizza delivery guy", "Boss", "Secretary", "Pregnancy", "Contraception", "Birth control pills", "IUD", "Patch", "Ring", "Pulling out", 
      "STD doctor", "Yeast infection", "Cystitis", "Prostatitis", "Hemorrhoids", "Fungus", "Smell", "Taste", "Size", "Girth", "Length", 
      "Curvature", "Hairiness"
    ]
  },
  es: {
    party: [
      "Resaca", "Tequila", "Chupito", "Barman", "Portero", "Control de acceso", "Pista de baile", "DJ", "Cachimba", "Vapeo", "Vómito", 
      "Helicópteros", "Sequedad", "Borrachera", "Fiesta en casa", "Afterparty", "Karaoke", "Resacón", "Barriga cervecera", "Jägermeister", 
      "Sambuca", "Absenta", "Brindis", "Chocar copas", "La del estribo", "Chupito de castigo", "Kalimotxo", "Destornillador", "Bloody Mary", 
      "Long Island", "Sexo en la playa", "Laguna azul", "Margarita", "Mojito", "Piña Colada", "Daiquiri", "Cosmopolitan", "B-52", "Hiroshima", 
      "Hada verde", "Ex novia", "Ex novio", "Friendzone", "Swipe", "Tinder", "Foto de polla", "Nudes", "Piropos", "Ligar", "Macho alfa", "Zorra", 
      "Calzonazos", "Cornudo", "Sugar daddy", "Mantenida", "Escort", "Amor de verano", "Romance de oficina", "Triángulo amoroso", "Infidelidad", 
      "Celos", "Pelea", "Sexo de reconciliación", "Chupetón", "Beso francés", "Arrumacos", "Cita", "Cena con velas", "Pétalos de rosa", 
      "Serenata", "Anillo", "Propuesta", "Despedida de soltero", "Despedida de soltera", "Boda", "Divorcio", "Pensión alimenticia", 
      "Prueba de ADN", "Sujetador", "Tanga", "Medias", "Corsé", "Louboutins", "Tacones de aguja", "Escote", "Minifalda", "Topless", "Bikini", 
      "Silicona", "Bótox", "Labios de pato", "Culo operado", "Tableta de chocolate", "Bíceps", "Tatuaje", "Piercing", "Cresta", "Barba", 
      "Bigote", "Calva", "Peluca", "Pestañas postizas", "Manicura", "Pedicura", "Depilación", "Depilación con azúcar", "Autobronceador", 
      "Solárium", "Hacer novillos", "Llegar tarde", "Fecha límite", "Estrés laboral", "Prima", "Multa", "Despido", "Entrevista de trabajo", 
      "Cena de empresa", "Team building", "Viaje de negocios", "Vacaciones", "Baja médica", "Baja por maternidad", "Hipoteca", "Crédito", 
      "Deudas", "Cobrador de deudas", "Juzgado", "Cárcel", "Abogado", "Fiscal", "Juez", "Soborno", "Comisión ilegal", "Malversación", 
      "Burocracia", "Cola", "Atasco", "Accidente de tráfico", "Seguro", "Reforma", "Vecinos", "Taladro", "Inundación", "Gratis", "Gorrón", 
      "Enchufe", "Contactos", "Postureo", "Hype", "Cringe", "ROFL", "Broma pesada", "Reto", "Stream", "Donación", "Hater", "Troll", "Bloguero", 
      "Influencer", "Tiktoker", "Instagramer", "Filtro", "Photoshop", "Selfie", "Stories", "Ricky Martin", "Britney Spears", "Madonna", 
      "Lady Gaga", "Freddie Mercury", "Michael Jackson", "Elvis Presley", "Marilyn Monroe", "Limusina", "Yate", "Jet privado", "Mansión", 
      "Ático", "Casino", "Ruleta", "Póker", "Blackjack", "Apuestas", "Bote", "Lotería", "Fortuna", "Suerte", "Buena racha", "Karma", "Destino", 
      "Horóscopo", "Adivina", "Vidente", "Amarre", "Mal de ojo", "Maldición", "Soltería eterna", "Soltero", "Solterona", 
      "Sin hijos por elección", "Madre helicóptero", "Obsesionada con bebés", "Pañal", "Chupete", "Carrito de bebé", "Maternidad", "Matrona", 
      "Ginecólogo", "Urólogo", "Proctólogo", "Dentista", "Psicólogo", "Psiquiatra", "Manicomio", "Camisa de fuerza", "Reina", "Príncipe", 
      "Princesa", "Cenicienta", "Blancanieves", "Sirenita", "Caramelo", "Chocolatina", "Gominola", "Nube", "Tarta", "Pastelito", "Dónut", 
      "Magdalena", "Galleta", "Gofre", "Pan de jengibre", "Turrón", "Helado", "Piruleta", "Chicle", "Sirope", "Mermelada", "Confitura", "Miel", 
      "Azúcar", "Pizza", "Hamburguesa", "Shawarma", "Sushi", "Rollitos", "Fideos", "Pasta", "Filete", "Brocheta", "Kebab", "Arroz pilaf", 
      "Borsch", "Ensalada Olivier", "Arenque con remolacha", "Gelatina de carne", "Crepes", "Tortitas", "Syrniki", "Pelmeni", "Vareniki", 
      "Plátano", "Fresa", "Frambuesa", "Cereza", "Sandía", "Melón", "Melocotón", "Albaricoque", "Ciruela", "Manzana", "Pera", "Naranja", 
      "Mandarina", "Limón", "Lima", "Pomelo", "Piña", "Kiwi", "Mango", "Coco", "Pepino", "Tomate", "Zanahoria", "Patata", "Cebolla", "Ajo", 
      "Pimiento", "Col", "Remolacha", "Guisantes", "Gato", "Perro", "Hámster", "Loro", "Pez", "Tortuga", "Conejo", "Rata", "Ratón", "Serpiente", 
      "Araña", "Cucaracha", "Mosquito", "Mosca", "Avispa", "Abeja", "Mariposa", "Hormiga", "Gusano", "Rana", "Tigre", "León", "Oso", "Lobo", 
      "Zorro", "Liebre", "Erizo", "Ardilla", "Ciervo", "Alce", "Elefante", "Jirafa", "Hipopótamo", "Rinoceronte", "Cebra", "Mono", "Canguro", 
      "Panda", "Koala", "Perezoso", "Casa", "Piso", "Casa de campo", "Garaje", "Cobertizo", "Baño ruso", "Sauna", "Piscina", "Valla", "Portón", 
      "Puerta", "Ventana", "Tejado", "Pared", "Suelo", "Techo", "Lámpara de araña", "Lámpara", "Enchufe", "Interruptor", "Sofá", "Sillón", 
      "Silla", "Mesa", "Cama", "Armario", "Cómoda", "Mesita de noche", "Estantería", "Espejo", "Alfombra", "Cortina", "Almohada", "Manta", 
      "Colchón", "Sábana", "Funda de almohada", "Toalla", "Albornoz", "Zapatillas", "Coche", "Autobús", "Tranvía", "Trolebús", "Metro", "Tren", 
      "Avión", "Helicóptero", "Barco", "Lancha", "Bicicleta", "Patinete", "Monopatín", "Patines", "Moto", "Ciclomotor", "Taxi", 
      "Coche compartido", "Semáforo", "Paso de peatones", "Señal de tráfico", "Carretera", "Puente", "Túnel", "Aparcamiento", "Gasolinera", 
      "Lavado de coches", "Taller", "Rueda", "Volante", "Freno", "Acelerador", "Embrague", "Caja de cambios", "Motor", "Faros", 
      "Limpiaparabrisas", "Maletero", "Capó", "Parachoques", "Móvil", "Tablet", "Portátil", "Ordenador", "Pantalla", "Teclado", "Ratón", 
      "Impresora", "Escáner", "Pendrive", "Disco", "Auriculares", "Altavoz", "Micrófono", "Cámara", "Cargador", "Cable", "Enchufe eléctrico", 
      "Pila", "Batería recargable", "WiFi", "Bluetooth", "Internet", "Página web", "Aplicación", "Juego", "Chat", "Correo", "Archivo", "Carpeta"
    ],
    dirty: [
      "Tetas", "Culo", "Polla", "Vagina", "Clítoris", "Pezones", "Pubis", "Periné", "Ano", "Huevos", "Escroto", "Glande", "Prepucio", "Frenillo", 
      "Punto G", "Próstata", "Útero", "Ovarios", "Trompas", "Coño", "Labios vaginales", "Vientre", "Pechos", "Caderas", "Cintura", "Ombligo", 
      "Cuello", "Oreja", "Lengua", "Labios", "Dientes", "Saliva", "Sudor", "Esperma", "Lubricante", "Flujo", "Regla", "Tampón", "Compresa", 
      "Lamer", "Chupar", "Follar", "Masturbarse", "Correrse", "Tragar", "Escupir", "Morder", "Arañar", "Azotar", "Apretar", "Frotar", 
      "Acariciar", "Besar", "Desnudar", "Quitarse", "Ponerse", "Meter", "Sacar", "Mover", "Mesa", "Silla", "Cama", "Sofá", "Sillón", "Suelo", 
      "Alfombra", "Ducha", "Bañera", "Lavabo", "Váter", "Lavadora", "Balcón", "Ventana", "Ascensor", "Portal", "Azotea", "Sótano", "Garaje", 
      "Coche", "Asiento trasero", "Capó", "Maletero", "Condón", "Lubricante", "Gel lubricante", "Aceite", "Crema", "Gel", "Velas", "Pétalos", 
      "Champán", "Fresas", "Nata montada", "Chocolate", "Hielo", "Esposas", "Látigo", "Mordaza", "Antifaz", "Máscara", "Disfraz", "Medias", 
      "Liguero", "Corsé", "Bustier", "Picardías", "Bata", "Toalla", "Sábana", "Manta", "Almohada", "Amante", "Amante", "Compañero sexual", 
      "Follamigo", "Rollo de una noche", "Polvo de una noche", "Virgen", "Virgen", "Experimentado", "Novato", "Tímida", "Guarra", "Ninfómana", 
      "Sátiro", "Gigoló", "Mantenido", "Prostituta", "Puta", "Zorra", "Perra", "Buscona", "Semental", "Mujeriego", "Don Juan", "Casanova", 
      "Seductor", "Orgasmo", "Erección", "Impotencia", "Viagra", "Cialis", "Excitación", "Pasión", "Lujuria", "Deseo", "Atracción", "Fantasía", 
      "Fetiche", "Complejos", "Tabúes", "Tabú", "Perversión", "Normalidad", "Patología", "Enfermedad", "Tratamiento", "Terapia", "Consulta", 
      "Consejo", "Experiencia", "Experimento", "Postura", "Kamasutra", "Misionero", "Vaquera", "Perrito", "69", "Vibrador", "Consolador", 
      "Plug anal", "Bolas chinas", "Bomba de vacío", "Electroestimulador", "Muñeca sexual", "Muñeca hinchable", "Mamada", "Cunnilingus", 
      "Beso negro", "Dedos", "Petting", "Voyeurismo", "Exhibicionismo", "Striptease", "Baile erótico", "Twerking", "Garganta profunda", "Squirt", 
      "Lluvia dorada", "Sexo telefónico", "Cibersexo", "Sexting", "Porno", "Hentai", "Erótica", "Casting", "Webcam", "OnlyFans", "Pornhub", 
      "Brazzers", "Sexo en grupo", "Trío", "Intercambio", "Intercambio de parejas", "Orgía", "Gangbang", "Sex shop", "Arnés", "Bondage", 
      "Shibari", "Azotes", "Bofetadas", "Mordiscos", "Chupetones", "Gemidos", "Gritos", "Suspiros", "Susurros", "Guarradas", "Juego de roles", 
      "Enfermera", "Profesora", "Criada", "Policía", "Fontanero", "Repartidor de pizza", "Jefe", "Secretaria", "Embarazo", "Anticoncepción", 
      "Pastillas", "DIU", "Parche", "Anillo", "Marcha atrás", "Venereólogo", "Candidiasis", "Cistitis", "Prostatitis", "Hemorroides", "Hongos", 
      "Olor", "Sabor", "Tamaño", "Grosor", "Largo", "Curvatura", "Vellosidad"
    ]
  },
  ua: {
    party: [
      "Похмілля", "Текіла", "Шот", "Бармен", "Вишибала", "Фейсконтроль", "Танцпол", "Діджей", "Кальян", "Вейп", "Блювота", "Вертольоти", 
      "Сушняк", "Запій", "Вписка", "Афтерпаті", "Караоке", "Бодунище", "Пивний живіт", "Єгермейстер", "Самбука", "Абсент", "Тост", "Чокатися", 
      "На коня", "Штрафна", "Йорш", "Викрутка", "Кривава Мері", "Лонг-Айленд", "Секс на пляжі", "Блакитна лагуна", "Маргарита", "Мохіто", 
      "Піна Колада", "Дайкірі", "Космополітен", "Б-52", "Хіросіма", "Зелена фея", "Колишня", "Колишній", "Френдзона", "Свайп", "Тіндер", 
      "Дікпік", "Нюдси", "Підкати", "Пікап", "Альфач", "Стерво", "Підкаблучник", "Рогоносець", "Папік", "Утриманка", "Ескорт", "Курортний роман", 
      "Службовий роман", "Любовний трикутник", "Зрада", "Ревнощі", "Сварка", "Примирливий секс", "Засос", "Французький поцілунок", "Обіймашки", 
      "Побачення", "Вечеря при свічках", "Пелюстки троянд", "Серенада", "Кільце", "Пропозиція", "Мальчишник", "Дівич-вечір", "Весілля", 
      "Розлучення", "Аліменти", "Тест ДНК", "Бюстгальтер", "Стрінги", "Панчохи", "Корсет", "Лабутени", "Шпильки", "Декольте", "Міні-спідниця", 
      "Топлес", "Бікіні", "Силікон", "Ботокс", "Губи качки", "Накачана дупа", "Кубики преса", "Біцепс", "Татуювання", "Пірсинг", "Ірокез", 
      "Борода", "Вуса", "Лисина", "Перука", "Накладні вії", "Манікюр", "Педикюр", "Епіляція", "Шугаринг", "Автозасмага", "Солярій", "Прогул", 
      "Запізнення", "Дедлайн", "Аврал", "Премія", "Штраф", "Звільнення", "Співбесіда", "Корпоратив", "Тімбілдінг", "Відрядження", "Відпустка", 
      "Лікарняний", "Декрет", "Іпотека", "Кредит", "Борги", "Колектори", "Суд", "В'язниця", "Адвокат", "Прокурор", "Суддя", "Хабар", "Відкат", 
      "Розпил", "Бюрократія", "Черга", "Затор", "ДТП", "Страховка", "Ремонт", "Сусіди", "Перфоратор", "Затопили", "Халява", "Шара", "Блат", 
      "Зв'язки", "Понти", "Хайп", "Крінж", "Рофл", "Пранк", "Челендж", "Стрім", "Донат", "Хейтер", "Троль", "Блогер", "Інфлюенсер", "Тіктокер", 
      "Інстаграмниця", "Фільтр", "Фотошоп", "Селфі", "Сторіз", "Рікі Мартін", "Брітні Спірс", "Мадонна", "Леді Гага", "Фредді Мерк'юрі", 
      "Майкл Джексон", "Елвіс Преслі", "Мерилін Монро", "Лімузин", "Яхта", "Джет", "Маєток", "Пентхаус", "Казино", "Рулетка", "Покер", 
      "Блекджек", "Ставки", "Джекпот", "Лотерея", "Фортуна", "Удача", "Фарт", "Карма", "Доля", "Гороскоп", "Ворожка", "Екстрасенс", "Приворот", 
      "Зглаз", "Порча", "Вінець безшлюбності", "Холостяк", "Стара діва", "Чайлдфрі", "Яжмать", "Овуляшка", "Підгузник", "Соска", "Візок", 
      "Пологовий", "Акушерка", "Гінеколог", "Уролог", "Проктолог", "Стоматолог", "Психолог", "Психіатр", "Дурдом", "Гамівна сорочка", "Королева", 
      "Принц", "Принцеса", "Попелюшка", "Білосніжка", "Русалонька", "Цукерка", "Шоколадка", "Мармелад", "Зефір", "Торт", "Тістечко", "Пончик", 
      "Кекс", "Печиво", "Вафлі", "Пряник", "Халва", "Морозиво", "Льодяник", "Жуйка", "Сироп", "Варення", "Джем", "Мед", "Цукор", "Піца", 
      "Бургер", "Шаурма", "Суші", "Роли", "Локшина", "Паста", "Стейк", "Шашлик", "Кебаб", "Плов", "Борщ", "Олів'є", "Оселедець під шубою", 
      "Холодець", "Млинці", "Оладки", "Сирники", "Пельмені", "Вареники", "Банан", "Полуниця", "Малина", "Вишня", "Кавун", "Диня", "Персик", 
      "Абрикос", "Слива", "Яблуко", "Груша", "Апельсин", "Мандарин", "Лимон", "Лайм", "Грейпфрут", "Ананас", "Ківі", "Манго", "Кокос", "Огірок", 
      "Помідор", "Морква", "Картопля", "Цибуля", "Часник", "Перець", "Капуста", "Буряк", "Горох", "Кішка", "Собака", "Хом'як", "Папуга", "Рибка", 
      "Черепаха", "Кролик", "Щур", "Миша", "Змія", "Павук", "Тарган", "Комар", "Муха", "Оса", "Бджола", "Метелик", "Мураха", "Черв'як", "Жаба", 
      "Тигр", "Лев", "Ведмідь", "Вовк", "Лисиця", "Заєць", "Їжак", "Білка", "Олень", "Лось", "Слон", "Жираф", "Бегемот", "Носоріг", "Зебра", 
      "Мавпа", "Кенгуру", "Панда", "Коала", "Лінивець", "Будинок", "Квартира", "Дача", "Гараж", "Сарай", "Лазня", "Сауна", "Басейн", "Паркан", 
      "Ворота", "Двері", "Вікно", "Дах", "Стіна", "Підлога", "Стеля", "Люстра", "Лампа", "Розетка", "Вимикач", "Диван", "Крісло", "Стілець", 
      "Стіл", "Ліжко", "Шафа", "Комод", "Тумбочка", "Полиця", "Дзеркало", "Килим", "Штора", "Подушка", "Ковдра", "Матрац", "Простирадло", 
      "Наволочка", "Рушник", "Халат", "Тапочки", "Машина", "Автобус", "Трамвай", "Тролейбус", "Метро", "Поїзд", "Літак", "Вертоліт", "Корабель", 
      "Човен", "Велосипед", "Самокат", "Скейт", "Ролики", "Мотоцикл", "Мопед", "Таксі", "Каршерінг", "Світлофор", "Перехід", "Знак", "Дорога", 
      "Міст", "Тунель", "Парковка", "Заправка", "Мийка", "Сервіс", "Колесо", "Кермо", "Гальмо", "Газ", "Зчеплення", "Коробка", "Двигун", "Фари", 
      "Двірники", "Багажник", "Капот", "Бампер", "Телефон", "Планшет", "Ноутбук", "Комп'ютер", "Монітор", "Клавіатура", "Мишка", "Принтер", 
      "Сканер", "Флешка", "Диск", "Навушники", "Колонка", "Мікрофон", "Камера", "Зарядка", "Кабель", "Розетка", "Батарейка", "Акумулятор", 
      "Вайфай", "Блютуз", "Інтернет", "Сайт", "Додаток", "Гра", "Чат", "Пошта", "Файл", "Папка"
    ],
    dirty: [
      "Цицьки", "Дупа", "Член", "Вагіна", "Клітор", "Соски", "Лобок", "Промежина", "Анус", "Яєчка", "Мошонка", "Голівка", "Крайня плоть", 
      "Вуздечка", "Точка G", "Простата", "Матка", "Яєчники", "Труби", "Піхва", "Статеві губи", "Лоно", "Груди", "Стегна", "Талія", "Пупок", 
      "Шия", "Вухо", "Язик", "Губи", "Зуби", "Слина", "Піт", "Сперма", "Змазка", "Виділення", "Місячні", "Тампон", "Прокладка", "Лизати", 
      "Смоктати", "Трахати", "Дрочити", "Кінчати", "Ковтати", "Спльовувати", "Кусати", "Дряпати", "Шльопати", "Стискати", "Терти", "Пестити", 
      "Цілувати", "Роздягати", "Знімати", "Одягати", "Вставляти", "Виймати", "Рухати", "Стіл", "Стілець", "Ліжко", "Диван", "Крісло", "Підлога", 
      "Килим", "Душ", "Ванна", "Раковина", "Унітаз", "Пральна машина", "Балкон", "Вікно", "Ліфт", "Під'їзд", "Дах", "Підвал", "Гараж", "Машина", 
      "Заднє сидіння", "Капот", "Багажник", "Презерватив", "Змазка", "Лубрикант", "Масло", "Крем", "Гель", "Свічки", "Пелюстки", "Шампанське", 
      "Полуниця", "Вершки", "Шоколад", "Лід", "Наручники", "Батіг", "Кляп", "Пов'язка", "Маска", "Костюм", "Панчохи", "Пояс", "Корсет", "Бюстьє", 
      "Пеньюар", "Халат", "Рушник", "Простирадло", "Ковдра", "Подушка", "Коханка", "Коханець", "Секс-партнер", "Секс по дружбі", 
      "Випадковий зв'язок", "Секс на одну ніч", "Незаймана", "Незайманий", "Досвідчений", "Недосвідчений", "Скромниця", "Розпусниця", 
      "Німфоманка", "Сатир", "Жиголо", "Альфонс", "Повія", "Шльондра", "Блядь", "Стерво", "Сучка", "Кобель", "Бабій", "Дон Жуан", "Казанова", 
      "Ловелас", "Оргазм", "Ерекція", "Імпотенція", "Віагра", "Сіаліс", "Збудження", "Пристрасть", "Хіть", "Бажання", "Потяг", "Фантазія", 
      "Фетиш", "Комплекси", "Заборони", "Табу", "Збочення", "Норма", "Патологія", "Хвороба", "Лікування", "Терапія", "Консультація", "Порада", 
      "Досвід", "Експеримент", "Поза", "Камасутра", "Місіонерська", "Наїзниця", "Доггі-стайл", "69", "Вібратор", "Фалоімітатор", 
      "Анальна пробка", "Вагінальні кульки", "Вакуумна помпа", "Електростимулятор", "Секс-лялька", "Гумова жінка", "Мінет", "Кунілінгус", 
      "Анілінгус", "Фінґерінг", "Петтінг", "Вуайеризм", "Ексгібіціонізм", "Стриптиз", "Лап-денс", "Тверк", "Глибока глотка", "Сквірт", 
      "Золотий дощ", "Секс по телефону", "Вірт", "Секстінг", "Порно", "Хентай", "Еротика", "Кастинги", "Вебкам", "Онліфанс", "Порнохаб", 
      "Браззерс", "Груповий секс", "Трійничок", "Свінг", "Обмін партнерами", "Оргія", "Ґенґбенґ", "Секс-шоп", "Страпон", "Бондаж", "Шибарі", 
      "Шмагання", "Ляпаси", "Укуси", "Засоси", "Стогони", "Крики", "Зітхання", "Шепіт", "Брудні слівця", "Рольові ігри", "Медсестра", 
      "Вчителька", "Покоївка", "Поліцейський", "Сантехнік", "Доставщик піци", "Бос", "Секретарка", "Вагітність", "Контрацепція", "Пігулки", 
      "Спіраль", "Пластир", "Кільце", "Перерваний акт", "Венеролог", "Молочниця", "Цистит", "Простатит", "Геморой", "Грибок", "Запах", "Смак", 
      "Розмір", "Товщина", "Довжина", "Кривизна", "Волохатість"
    ]
  }
};

// Backward-compatible alias (deprecated - use getWordDatabase() from remoteDictionary.ts)
export const WORD_DATABASE = DEFAULT_WORD_DATABASE;
